runtime: python27
api_version: '1'
env: standard
threadsafe: true
instance_class: F1
handlers:
  - url: /.*
    script: main.app
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 0
  min_pending_latency: 10s
  max_pending_latency: 10s
  max_concurrent_requests: 50
  target_cpu_utilization: 0.6
  min_instances: 1
  max_instances: 100
network: {}